name: Tag and Release Lightless

on:
  push:
    branches: [ master ]

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: checkout lightless
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: get version from lightless proj
      id: get_version
      uses: KageKirin/get-csproj-version@v0
      with:
        file: LightlessSync/LightlessSync.csproj
        

    - name: Create Git tag
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git tag ${{ steps.test.get_version.version }}
        git push origin "${VERSION}"
      env:
        VERSION: ${{ env.VERSION }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.test.get_version.version }}
        name: Release ${{ steps.test.get_version.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}