name: Tag and Release Lightless

on:
  push:
    branches: [ master ]

env:
  PLUGIN_NAME: LightlessSync
  DOTNET_VERSION: 9.x
  SOLUTION_PATH: LightlessSync.sln

jobs:
  tag-and-release:
    runs-on: windows-2022

    steps:
    - name: Checkout Lightless
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Install dependencies
      run: dotnet restore

    - name: Build LightlessSync
      run: dotnet build --configuration Release --no-restore

    - name: Publish LightlessSync
      run: dotnet publish --configuration Release --no-build --output publish_output
    
    - name: Get version
      id: package_version
      uses: KageKirin/get-csproj-version@v0
      with:
        file: LightlessSync/LightlessSync.csproj

    - name: Display version
      run: | 
          echo "Version: ${{ steps.package_version.outputs.version }}"

    # - name: Create Git tag
    #   run: |
    #     echo "Tagging version ${{ steps.get_version.version }}"
    #     git config user.name "GitHub Action"
    #     git config user.email "action@github.com"
    #     git tag ${{ steps.test.get_version.version }}
    #     git push origin ${{ steps.test.get_version.version }}

    # - name: Create GitHub Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     tag_name: ${{ steps.test.get_version.version }}
    #     name: Release ${{ steps.test.get_version.version }}
    #     draft: false
    #     prerelease: false
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}